const Map<String, String> gatheredVoices = {
  "en-us-x-iob-network": "US Network B",
  "en-AU-language": "AU Language",
  "en-us-x-iol-network": "US Network L",
  "en-us-x-iom-network": "US Network M",
  "en-GB-language": "GB Language",
  "en-NG-language": "NG Language",
  "en-in-x-enc-local": "IN Local C",
  "en-gb-x-gba-network": "GB Network A",
  "en-us-x-iom-local": "US Local M",
  "en-au-x-auc-network": "AU Network C",
  "en-in-x-enc-network": "IN Network C",
  "en-in-x-ene-network": "IN Network E",
  "mai-in-x-end-local": "IN Local D",
  "en-ng-x-tfn-network": "NG Network F",
  "en-US-language": "US Language",
  "en-gb-x-gbc-network": "GB Network C",
  "en-au-x-aua-network": "AU Network A",
  "sat-in-x-end-local": "IN Local S",
  "en-ng-x-tfn-local": "NG Local F",
  "brx-in-x-end-local": "IN Local B",
  "en-us-x-tpd-local": "US Local D",
  "en-au-x-aua-local": "AU Local A",
  "ks-in-x-end-local": "IN Local K",
  "kok-in-x-end-local": "IN Local KOK",
  "en-in-x-ena-network": "IN Network A",
  "sa-in-x-end-local": "IN Local SA",
  "en-au-x-aud-local": "AU Local D",
  "en-us-x-iog-network": "US Network G",
  "en-us-x-tpf-network": "US Network F",
  "en-IN-language": "IN Language",
  "sd-in-x-end-local": "IN Local SD",
  "en-gb-x-rjs-network": "GB Network RJS",
  "en-us-x-sfg-network": "US Network SFG",
  "en-gb-x-rjs-local": "GB Local RJS",
  "doi-in-x-end-local": "IN Local DOI",
  "en-us-x-sfg-local": "US Local SFG",
  "en-La-x-ene-local": "LA Local E",
  "en-gb-x-gbg-local": "GB Local G",
  "en-us-x-iob-local": "US Local B",
  "en-gb-x-gbd-local": "GB Local D",
  "en-gb-x-gbd-network": "GB Network D",
  "en-us-x-tpd-network": "US Network D",
  "en-us-x-tpc-network": "US Network C",
  "en-in-x-end-local": "IN Local D",
  "en-gb-x-gbb-local": "GB Local B",
  "or-in-x-end-local": "IN Local OR",
  "en-au-x-aub-local": "AU Local B",
  "en gb-x-gbc-local": "GB Local C",
  "en-gb-x-gba-local": "GB Local A",
  "en-gb-x-gbb-network": "GB Network B",
  "en-us-x-tpf-local": "US Local F",
  "en-in-x-end-network": "IN Network D",
  "en-au-x-aub-network": "AU Network B",
  "en-au-x-auc-local": "AU Local C",
  "mni-in-x-end-local": "IN Local M",
  "en-au-x-aud-network": "AU Network D",
};
